[package]
name = "aptos-flow"
version = "1.0.0"
authors = []

[addresses]
my_aptos_project = "0x440574625c46ef4d3429df220686eab520ef1d54d60893470d1701537c629337"
deployer = "0x440574625c46ef4d3429df220686eab520ef1d54d60893470d1701537c629337"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

